services:
  - type: web
    name: login-system
    env: node
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: your-db-host
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_NAME
        value: login_system
      - key: JWT_SECRET
        value: your-jwt-secret
